server:
  port: 8701
spring:
  application:
    name: feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://yyc:123@localhost:8001/eureka/
feign:
  hystrix:
    enabled: true
logging:
  level:
    com.learnspringcloud.feignservice.service.UserService: debug
