server:
  port: 8002
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica2
  client:
    fetch-registry: true       # 是否检索服务
    register-with-eureka: true # 是否注册
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
