server:
  port: 8003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica3
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://replica3:8002/eureka
